//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desk { get; set; }
        public string Pres { get; set; }
        public string Price { get; set; }
        public int IdUsers { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
